apiVersion: v1
kind: Secret
metadata:
  name: cast-secret
  namespace: {{ .Values.nameSpace }}
type: kubernetes.io/basic-auth
stringData:
  username: 'cast_db_username'
  password: 'cast_db_password'
